### ISSUE TITLE
Unable to get NSQL to work on Windows 10

### ISSUE THREAD

**Issue by harnitbakshi** [NumbersStationAI/NSQL#18]
I am trying to run NSQL on my windows 10 Razor laptop, but I was unable to install DeepSpeed. I managed to work around that but now when I try to open the webserver link in U/I I get this error:
`
[2023-12-02 07:38:57,987] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pkg_resources\__init__.py", line 402, in get_provider
    module = sys.modules[moduleOrReq]
  File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\manifest\api\app.py", line 295, in index
    fn = pkg_resources.resource_filename("metaseq", "service/index.html")
  File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pkg_resources\__init__.py", line 1213, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pkg_resources\__init__.py", line 404, in get_provider
    __import__(moduleOrReq)
ModuleNotFoundError: No module named 'metaseq'
`

Tried installing metaseq, but got the error

```
(NSQL-310) PS C:\Users\User\PycharmProjects\NSQL> pip install metaseq
Collecting metaseq
  Using cached metaseq-0.5.6.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy>=0.10.1 in c:\users\user\pycharmprojects\nsql\venv\pycharmprojects\nsql-310\lib\site-packages (from metaseq) (1.11.4)
Collecting biopython (from metaseq)
  Using cached biopython-1.81-cp310-cp310-win_amd64.whl (2.7 MB)
Requirement already satisfied: scikit-learn in c:\users\user\pycharmprojects\nsql\venv\pycharmprojects\nsql-310\lib\site-packages (from metaseq) (1.3.2)
Collecting bx-python>=0.7.1 (from metaseq)
  Using cached bx-python-0.10.0.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Cython (from metaseq)
  Using cached Cython-3.0.6-cp310-cp310-win_amd64.whl.metadata (3.2 kB)                                                                                  
Requirement already satisfied: numpy>=1.8.0 in c:\users\user\pycharmprojects\nsql\venv\pycharmprojects\nsql-310\lib\site-packages (from metaseq) (1.26.2)
Collecting matplotlib>=1.3.1 (from metaseq)
  Using cached matplotlib-3.8.2-cp310-cp310-win_amd64.whl.metadata (5.9 kB)
Requirement already satisfied: pandas>=0.13.1 in c:\users\user\pycharmprojects\nsql\venv\pycharmprojects\nsql-310\lib\site-packages (from metaseq) (2.1.3)
Collecting pysam>=0.7 (from metaseq)
  Using cached pysam-0.22.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\User\PycharmProjects\NSQL\venv\PycharmProjects\NSQL-310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_
build_wheel
          return hook(config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-p3fehn45\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
          exec(code, locals())
        File "<string>", line 442, in <module>
        File "<string>", line 82, in run_make_print_config
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Does NSQL only work on Linux or Mac?

**Comment by senwu** [comment]
Thanks for your interest in our project!

The ModuleNotFoundError: No module named 'metaseq' issue is from manifest not the NSQL. We will take a look at the issue there but it should not affect the usage of the NSQL model meaning that the manifest is still running even it throws that error.
